name: central-system
services:
  central-module:
    build:
      context: .
    environment:
      KAFKA_BROKER_ADDRESS: kafka_container:9092
    ports:
      - "8081:8080"
    depends_on:
      - kafka

  zookeeper:
    image: zookeeper:3.8.2
    container_name: zookeeper
    restart: no
    volumes:
      - /data/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_container
    restart: no
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
