gateway:
  routes:
    - name: calculation-application-route
      mappingUrl: /calculations-db-access
      applicationUrl: ${calculation.database.application.address}

    - name: mediative-module
      mappingUrl: /mediative-module
      applicationUrl: ${mediative.module.application.address}
