gateway:
  routes:
    - name: calculation-application-route
      mappingUrl: /calculations-db-access
      applicationUrl: ${calculation.database.application.address}

    - name: mediative-module
      mappingUrl: /mediative-module
      applicationUrl: ${mediative.module.application.address}

    - name: real-time-calculations
      mappingUrl: /real-time-calculations
      applicationUrl: ${real.time.calculations.address}

    - name: prediction-module
      mappingUrl: /prediction-module
      applicationUrl: ${prediction.module.address}
